### ISSUE TITLE
Not able to install the package qtl2peio

### ISSUE THREAD

**Issue by HongHe0123** [fboehm/qtl2pleio#22]
Could you please help me with the installation? Thanks. I used devtools::install_github("fboehm/qtl2pleio") to install the package. But have an error as follows: 

C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"C:/Users//Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users//Documents/R/win-library/3.5/RcppEigen/include"        -O2 -Wall  -mtune=generic -c test-example.cpp -o test-example.o
test-example.cpp:12:22: **_**fatal error: testthat.h: No such file or directory**_**
 #include <testthat.h>
                      ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.3/etc/i386/Makeconf:215: test-example.o] Error 1
ERROR: compilation failed for package 'qtl2pleio'
* removing 'C:/Users//Documents/R/win-library/3.5/qtl2pleio'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users//AppData/Local/Temp/RtmpoX3waK/file5389835017109/qtl2pleio_1.0.7.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by fboehm** [comment]
Hello,

Thanks for reaching out for assistance. I'm delighted that you're interested in using qtl2pleio.

Thank you for bringing this to my attention. I will work on it today and update tonight. 

In the mean time, can you tell me which operating system and which version of R you are using? It might not matter - I'm not yet sure what the underlying problem is.

Thanks again!

**Comment by fboehm** [comment]
I successfully installed an earlier commit by using this R code:

```
install_github("fboehm/qtl2pleio", ref = "b7ce5bdba3b5a120a58af0f0337b72ac30cfed1a")
```

For today, I suggest using it. I need more time to work on a more robust solution.

**Comment by HongHe0123** [comment]
Thank you so much for your quick response. The old version of qtl2pleio is successfully installed in my computer. 

My system is Windows 10 Pro
Version of R is “R version 3.5.3 (2019-03-11)”

Thanks for your help!

**Comment by fboehm** [comment]
This is now fixed. You should be able to install the package directly from the master branch.
