### ISSUE TITLE
How to "Create a profile LOD plot to visualize results of two-dimensional scan"?

### ISSUE THREAD

**Issue by HongHe0123** [fboehm/qtl2pleio#23]
The R code for "Create a profile LOD plot to visualize results of two-dimensional scan" is missing at webpage https://github.com/fboehm/qtl2pleio. Can I know how you created the figure? Thanks!

![](https://raw.githubusercontent.com/fboehm/qtl2pleio/master/man/figures/README-profile-plot-1.png)

**Comment by HongHe0123** [comment]
I think I figured it out :) Thanks!

temp2=tidy_scan_pvl(out, pm = DOex$pmap) 
temp2$marker_position=rep(DOex$pmap$`3`[38:(38+24)],3)

ggplot(data=temp2, aes(x = marker_position, y =lod, color = Trace, linetype=Trace) )+
  geom_line() +
  xlab("Chromosome positon (Mb)") +
  ylab("LOD")

**Comment by fboehm** [comment]
Great! I also wrote a function `plot_pvl` that creates the figure. To read its help page, type `?plot_pvl` at the R prompt (after loading `qtl2pleio`. Also, be sure to check out the vignettes to see examples of its use.
