### ISSUE TITLE
tidy_scan_pvl does not deal with more than two traits

### ISSUE THREAD

**Issue by HongHe0123** [fboehm/qtl2pleio#24]
From my understanding, the function scan_pvl works with more than two traits. But the function tidy_scan_pvl only works with two traits. Can it expand to at least 4 traits? Thanks!!

**Comment by fboehm** [comment]
yes, the current version of `tidy_scan_pvl` accepts results from only bivariate analyses. Let me work on editing the code to allow for k-variate analyses. And yes, you're right about `scan_pvl`. It currently allows for k-variate analysis.

**Comment by fboehm** [comment]
Thanks for opening this issue. I've made the fixes to the code base that were needed. You should now be able to do a d-variate (d >= 2) analysis. Just follow the code in the vignette "d-variate-analysis.Rmd" after installing the new version of the package from github. 

Please let me know if you encounter any difficulties in your analysis.

thanks again!
